// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8FBMLJv-T2jzbrVigkcvlboK0eKO0Ovs',
    appId: '1:912395451551:web:4ab3fd9a99ab0e1f01f6aa',
    messagingSenderId: '912395451551',
    projectId: 'friendless-cfbb4',
    authDomain: 'friendless-cfbb4.firebaseapp.com',
    storageBucket: 'friendless-cfbb4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7apio1ChA8WQ55nMDjLZNghcTJ0E1Uuw',
    appId: '1:912395451551:android:daeb69a47a7bc08f01f6aa',
    messagingSenderId: '912395451551',
    projectId: 'friendless-cfbb4',
    storageBucket: 'friendless-cfbb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhGwA9Hu2dJYCJ-KF2AHca5iFQQMvJ39c',
    appId: '1:912395451551:ios:2b2e67062c14efe001f6aa',
    messagingSenderId: '912395451551',
    projectId: 'friendless-cfbb4',
    storageBucket: 'friendless-cfbb4.appspot.com',
    iosBundleId: 'com.example.friendless',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhGwA9Hu2dJYCJ-KF2AHca5iFQQMvJ39c',
    appId: '1:912395451551:ios:2b2e67062c14efe001f6aa',
    messagingSenderId: '912395451551',
    projectId: 'friendless-cfbb4',
    storageBucket: 'friendless-cfbb4.appspot.com',
    iosBundleId: 'com.example.friendless',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8FBMLJv-T2jzbrVigkcvlboK0eKO0Ovs',
    appId: '1:912395451551:web:92edefb43e245aa501f6aa',
    messagingSenderId: '912395451551',
    projectId: 'friendless-cfbb4',
    authDomain: 'friendless-cfbb4.firebaseapp.com',
    storageBucket: 'friendless-cfbb4.appspot.com',
  );

}